language: shell
services:
  - docker

install:
  - docker build -t docker-chromium .
  - docker run -it docker-chromium

notifications:
  email:
    recipients:
      - gb8may@gmail.com
      - jehnyffen@gmail.com
 
    on_success: always
    on_failure: always

cache:
  apt: true
  directories:
  - ~/.docker
  - ~/.cache
