language: shell
services:
  - docker

install:
  - docker build -t docker-chromium . #construcao do arquivo de imagem a partir do arquivo Dockerfile no diretorio corrente.
  - docker run -it docker-chromium #Execucao do container no modo iterativo para visualizacao de logs.

notifications:
  email:
    recipients:
      - gb8may@gmail.com
      - jehnyffen@gmail.com
 
    on_success: always
    on_failure: always

cache:
  apt: true
  directories:
  - ~/.docker
  - ~/.cache
