language: bash
sudo: required
services:
  - docker

testSmokeCy: &testSmokeCy
  install:
  - docker run -it --rm --name labjava -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean install
  - kill $(jobs -p) || true

jobs:
  fast_finish: true
  allow_failures:
  include:
  - script:
    name: "Maven Container 1"
    <<: *testSmokeCy
  - script:
    name: "Maven Container 2"
    <<: *testSmokeCy  

notifications: 
  email:
    recipients:
      - gb8may@gmail.com
      - jehnyffen@gmail.com
 
    on_success: always
    on_failure: always

cache:
  apt: true
  docker: true
  directories:
  - ~/.docker
  - ~/.cache
